name = "Boat"
author = "TheCostco & SkyCloud53"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e309866aecbe9e6b4434c8cac6bcdfb06674a1e9d2d4e61b0c8d6895b048530e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
