name = "Boat"
author = "TheCostco & SkyCloud53"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ee5a5b758bb8df5d86cdc7cdb5d4ef10582167264280eb63f8c3d1aa882b8e3"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
