name = "scurvy"
author = "emer"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a81467902e876a32e8be228d237d2c7d07b4ce3d5ccf9a23397c87473f3bd683"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
